# -*- coding: utf-8 -*-
"""NLP_Project_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ko1I7GXVEnD7yNWRJ27tqEY9kuUGV3Ag
"""

# 0) 환경 확인
# ----------------------------
!nvidia-smi || true
!cat /etc/os-release | head -n 3
!python --version

# 1) 패키지 설치
#    - langchain / langgraph / chroma / pymupdf
# ----------------------------
!pip -q install -U \
  langchain langchain-core langchain-community \
  langchain-ollama langchain-chroma \
  langgraph \
  pymupdf \
  pydantic \
  datasets ragas

# 2) Ollama 설치 + 서버 기동 + 모델 pull (에러 방지)
# ----------------------------
import os, time, subprocess, json, urllib.request

# zstd 설치 (ollama 설치 스크립트에서 요구할 수 있음)
!sudo apt-get update -y >/dev/null
!sudo apt-get install -y zstd curl >/dev/null

# ollama 설치
!curl -fsSL https://ollama.com/install.sh | sh

def is_ollama_up(url="http://127.0.0.1:11434/api/tags", timeout=2) -> bool:
    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:
            _ = resp.read(200)
        return True
    except Exception:
        return False

# 서버가 이미 떠있으면 다시 띄우지 않음
if not is_ollama_up():
    # 백그라운드로 실행
    _ = subprocess.Popen(["ollama", "serve"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    time.sleep(2)

# 최종 확인 (여기서 실패하면 이후가 다 안됨)
assert is_ollama_up(), "❌ Ollama server가 떠있지 않습니다. 'ollama serve'가 실패했어요."

# 모델 pull (없으면 자동으로 받음)
!ollama pull llama3
!ollama pull nomic-embed-text

print("✅ Ollama ready")

# 3) Google Drive 마운트 + PDF 로드 (경로/파일 체크 포함)
# ----------------------------
!pip install pypdf
from google.colab import drive
from langchain_community.document_loaders import PyPDFLoader

drive.mount("/content/drive")
pdf_path = "/content/drive/MyDrive/[GW_INSTEK]GPT-9800-SERIES_USER-MANUAL_KR.pdf"
loader = PyPDFLoader(pdf_path)

if not os.path.exists(pdf_path):
    raise FileNotFoundError(
        f"❌ PDF를 못 찾음: {pdf_path}\n"
        "Drive 경로/파일명을 확인하고 PDF_PATH를 수정하세요."
    )


loader = PyPDFLoader(pdf_path)
documents = loader.load()
print("✅ Manual pages:", len(documents))
assert len(documents) > 0, "❌ PDF에서 페이지를 못 읽었습니다. (암호화/손상 가능)"

# 데이터 준비
import pandas as pd
import numpy as np

np.random.seed(42)

# ----- Constants -----
EQPID = "KR-010101"
MODEL = "LGMONYTV"
Program_Version = "260206"
Equipment_Version = "M.KOR"
Spec_Min_mA = 0.80
Spec_Max_mA = 10.00

def make_row(i, label, s6f1_result, saved_result, delta_s, acw):
    return {
        "issue_id": f"{i:03d}",
        "label": label,  # OK / NG (정답 라벨)
        "EQPID": EQPID,
        "SETID": f"500MONY{i:04d}",
        "MODEL": MODEL,
        "Program_Version": Program_Version,
        "Equipment_Version": Equipment_Version,
        "S6F12_ACK": 0,
        "delta_S6F11_S6F12_s": int(delta_s),
        "S6F1_RESULT": s6f1_result,     # 장비 판단
        "ACW_Mea_mA": round(float(acw), 2),
        "Spec_Min_mA": Spec_Min_mA,
        "Spec_Max_mA": Spec_Max_mA,
        "Saved_Result": saved_result,   # 저장 결과
    }

rows = []

# ----- OK 데이터 100개 (001~100): RESULT=OK, Saved=OK -----
ok_acw = np.clip(
    np.random.normal(loc=4.5, scale=2.0, size=100),
    Spec_Min_mA + 0.01, Spec_Max_mA - 0.01
)
ok_delta = np.random.choice([1, 2, 3], size=100, p=[0.6, 0.3, 0.1])

for idx in range(1, 101):
    rows.append(make_row(idx, "OK", "OK", "OK", ok_delta[idx-1], ok_acw[idx-1]))

# ----- NG 데이터 10개 (101~110)
#  - mismatch 6개: S6F1 OK but Saved NG
#  - true NG 4개: S6F1 NG and Saved NG
ng_plan = {
    101: ("NG", "OK", "NG", 1, 3.10),
    102: ("NG", "OK", "NG", 2, 4.62),
    103: ("NG", "NG", "NG", 1, 2.40),
    104: ("NG", "OK", "NG", 3, 9.12),
    105: ("NG", "NG", "NG", 1, 6.07),
    106: ("NG", "OK", "NG", 2, 2.88),
    107: ("NG", "NG", "NG", 1, 1.05),
    108: ("NG", "OK", "NG", 2, 7.41),
    109: ("NG", "NG", "NG", 1, 3.77),
    110: ("NG", "OK", "NG", 2, 5.18),
}

for idx in range(101, 111):
    label, s6f1_result, saved_result, delta_s, acw = ng_plan[idx]
    # 스펙은 정상 찍히는 조건 유지(스펙 범위 내로 클립)
    acw = min(max(acw, Spec_Min_mA + 0.01), Spec_Max_mA - 0.01)
    rows.append(make_row(idx, label, s6f1_result, saved_result, delta_s, acw))

df = pd.DataFrame(rows)

# 파생 컬럼: mismatch 여부 / 케이스 타입
df["is_mismatch"] = ((df["S6F1_RESULT"] != df["Saved_Result"]) & (df["label"] == "NG")).astype(int)
df["case_type"] = np.where(
    df["label"] == "OK",
    "ok_normal",
    np.where(df["is_mismatch"] == 1, "mismatch_ok_saved_ng", "true_ng_s6f1_ng")
)

# ----- CSV 저장 -----
out_path = "/content/inspection_logs_110.csv"
df.to_csv(out_path, index=False, encoding="utf-8-sig")

print("Saved:", out_path)
df.head(10)

# 5) Split + Vectorstore (Chroma) - Ollama Embeddings 사용
# ----------------------------
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_ollama import ChatOllama, OllamaEmbeddings
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=100,
    separators=["\n\n", "\n", " ", ""]
)
splits = splitter.split_documents(documents)
print("✅ chunks:", len(splits))
assert len(splits) > 0, "❌ split 결과가 0입니다."


embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

vectorstore = Chroma.from_documents(
    documents=splits,
    embedding=embeddings,
    persist_directory="/content/chroma_gpt9800_manual"
)

print("Vector DB ready:", vectorstore._collection.count())

from langchain_community.chat_models import ChatOllama

# Baseline은 llama3
llm_baseline = ChatOllama(model="llama3", temperature=0.2)

# Agentic은 tools 지원 모델
llm_agent = ChatOllama(model="llama3.1:8b", temperature=0.2)

# 6) Baseline (Vanilla + RAG chain)
# =========================
from langchain_ollama import ChatOllama
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough, RunnableLambda
from langchain_core.documents import Document
from typing import List


llm = ChatOllama(model="llama3", temperature=0.2)

retriever = vectorstore.as_retriever(search_kwargs={"k": 4})

def format_docs(docs: List[Document]) -> str:
    blocks = []
    for d in docs:
        src = d.metadata.get("source", "manual_pdf")
        page = d.metadata.get("page", None)
        page_str = f"page={page}" if page is not None else ""
        blocks.append(f"[manual] source={src} {page_str}\n{d.page_content}")
    return "\n\n---\n\n".join(blocks)

baseline_template = """너는 GPT-9804 검사 장비 전문가야.
MANUAL(pdf파일) 내용에 근거해서만 답변해.
MANUAL에 없는 내용은 절대 단정해서 말하지 말고 '추가 확인 필요'라고 말해.

반드시 아래 형식으로만 출력:
▶ 요약
...
▶ 원인
...
▶ 원인 분석 evidence
1) ...
2) ...
▶ 임시 방안
...
▶ 추가 필요 사항
...

MANUAL:
{context}

QUESTION:
{question}
"""

baseline_prompt = ChatPromptTemplate.from_template(baseline_template)

baseline_rag_chain = (
    {
        "context": retriever | RunnableLambda(format_docs),
        "question": RunnablePassthrough()
    }
    | baseline_prompt
    | llm_baseline
    | StrOutputParser()
)

print("✅ Baseline RAG chain ready.")

# 7) Agentic
# =========================
from langchain.tools import tool
from langchain.tools import BaseTool
from typing import Dict, Any, List, Optional
import json, re

@tool
def manual_retrieve_tool(query: str) -> str:
    """매뉴얼에서 관련 chunk만 가져와 반환 (답변 생성 X)"""
    docs = retriever.invoke(query)
    if not docs:
        return "NO_CONTEXT_FOUND"
    return "\n\n---\n\n".join(d.page_content for d in docs)

@tool
def inspection_log_tool(_: str = "") -> str:
    """df 기반 mismatch/NG 요약"""
    total = len(df)
    ng = int((df["label"] == "NG").sum())
    mismatch = int(df["is_mismatch"].sum())
    sample = df[df["is_mismatch"] == 1][
        ["issue_id", "SETID", "S6F1_RESULT", "Saved_Result", "ACW_Mea_mA"]
    ].head(5)
    return f"""
[Inspection Summary]
- Total: {total}
- NG: {ng}
- Mismatch: {mismatch}

[Sample]
{sample.to_string(index=False)}
""".strip()

@tool
def extract_log_signals_tool(text: str) -> str:
    """로그 텍스트에서 ack / SxFy / LO/HI SET 힌트 추출(문자열로 반환)"""
    ack = re.findall(r"\back\s*[:=]?\s*(\d+)\b", text, flags=re.I)
    secs = re.findall(r"\bS\d+F\d+\b", text, flags=re.I)
    params = re.findall(r"\b(LO\s*SET|HI\s*SET)\b", text, flags=re.I)
    return json.dumps({
        "ack": int(ack[-1]) if ack else None,
        "secs_messages": sorted(list(set([s.upper() for s in secs]))) if secs else [],
        "params": sorted(list(set([p.upper().replace(" ", "") for p in params]))) if params else [],
        "log_len": len(text)
    }, ensure_ascii=False)

TOOLS: Dict[str, BaseTool] = {
    "manual_retrieve_tool": manual_retrieve_tool,
    "inspection_log_tool": inspection_log_tool,
    "extract_log_signals_tool": extract_log_signals_tool,
}

def extract_json_objects(text: str) -> List[Dict[str, Any]]:
    objs = []
    for m in re.finditer(r"\{[,]?[\s\S]*?\}", text):
        s = m.group()
        try:
            obj = json.loads(s)
            if isinstance(obj, dict):
                objs.append(obj)
        except Exception:
            continue
    return objs

def extract_final(text: str) -> Optional[str]:
    objs = extract_json_objects(text)
    for obj in reversed(objs):
        if "final" in obj and isinstance(obj["final"], str):
            return obj["final"]
    return None

def extract_tool_call(text: str) -> Optional[Dict[str, str]]:
    objs = extract_json_objects(text)
    for obj in reversed(objs):
        t = obj.get("tool")
        if t in TOOLS:
            inp = obj.get("input", "")
            if not isinstance(inp, str):
                inp = str(inp)
            return {"tool": t, "input": inp}
    return None

def agentic_react(question: str, max_steps: int = 4) -> str:
    memory = ""
    used_tools = set()

    def final_answer() -> str:
        return llm.invoke(
f"""
너는 GPT-9800 검사 장비 트러블슈팅 전문가다.
아래 OBSERVATIONS(매뉴얼 발췌/로그 요약/검사이력)에 근거해서만 답하라.
OBSERVATIONS에 근거가 없으면 반드시 '추가 확인 필요'로 남겨라.

OBSERVATIONS:
{memory}

USER QUESTION:
{question}

반드시 아래 형식으로만 출력:
▶ 요약
...
▶ 원인
...
▶ 원인 분석 evidence
1) ...
2) ...
▶ 임시 방안
...
▶ 추가 필요 사항
...
"""
        ).content

    for _ in range(max_steps):
        prompt = f"""
너는 GPT-9800 트러블슈팅 에이전트다. 반드시 아래 순서로 진행해라:

1) extract_log_signals_tool로 ACK/SxFy 신호 추출
2) 추출 신호를 포함해 manual_retrieve_tool 검색 쿼리를 재작성해서 매뉴얼 근거를 확보
3) 필요 시 inspection_log_tool로 이력(mismatch) 확인
4) 근거가 충분하면 {{\"final\":\"READY\"}} 를 출력해라 (READY면 시스템이 최종답을 생성한다)

OBSERVATIONS:
{memory}

QUESTION:
{question}

가능한 출력(JSON 하나):
{{\"tool\":\"extract_log_signals_tool\",\"input\":\"질문에서 로그/ACK/S6F 포함 부분\"}}
{{\"tool\":\"manual_retrieve_tool\",\"input\":\"ACK/S6F 포함 재작성 쿼리\"}}
{{\"tool\":\"inspection_log_tool\",\"input\":\"\"}}
{{\"final\":\"READY\"}}
"""
        resp = llm.invoke(prompt).content

        fin = extract_final(resp)
        if fin is not None:
            return final_answer()

        call = extract_tool_call(resp)
        if call is None:
            return final_answer()

        tname, tin = call["tool"], call["input"]
        if tname in used_tools:
            return final_answer()

        used_tools.add(tname)
        obs = TOOLS[tname].invoke(tin)
        memory += f"\n[{tname}]\n{obs}\n"

    return final_answer()

print("✅ Agentic(JSON-ReAct) ready")

# 8) 비교 실행 (Baseline vs Agentic)
# =========================
q1 = "[현상]SETID 스캔은 정상적으로 완료되었으나 검사 동작이 되지 않음. [로그]10:21:14  S6F11  SETID=500MONY0051, 10:21:15  S6F12  ACK=1 [운영조건] Program Version: 260206, Equipment Version: M.KOR, 동일 SETID로 재시도 시 동일 현상 발생 [질문] 로그 기준으로 S6F12 ACK=1 이 왜 발생했는지, 확인해야할 매뉴얼 항목 및 점검 절차를 알려줘"

print("="*60)
print("Baseline")
print("="*60)
print(baseline_rag_chain.invoke(q1))

print("\n" + "="*60)
print("Agentic")
print("="*60)
print(agentic_react(q1))

# human score

import pandas as pd
import numpy as np

RUBRIC = [
    ("correctness",  "원인/조치가 논리적으로 타당한가?"),
    ("evidence",     "매뉴얼/로그 근거를 인용/연결했는가? (환각 적은가)"),
    ("actionability","현장에서 바로 실행 가능한 절차/체크가 있는가?"),
    ("safety",       "근거 없이 단정/위험한 조치를 말하지 않는가?")
]

def make_human_eval_sheet_single(
    question,
    baseline_answer,
    agentic_answer,
    rubric=RUBRIC
):
    row = {
        "case_id": "C001",
        "question": question,
        "log": "",
        "baseline_answer": baseline_answer,
        "agentic_answer": agentic_answer,
        "preference(agentic_vs_baseline)": "agentic",
        "notes": ""
    }

    for key, _ in rubric:
        row[f"baseline_{key}(1-5)"] = 3
        row[f"agentic_{key}(1-5)"]  = 3

    return pd.DataFrame([row])



human_df = make_human_eval_sheet_single(
    q1,
    baseline_rag_chain.invoke(q1),
    agentic_react(q1)
)


print("✅ Human eval sheet created.")
print("👉 Fill preference: Win / Lose / Tie")
print("👉 Fill scores: 1 (매우 나쁨) ~ 5 (매우 우수)")


human_df







