# -*- coding: utf-8 -*-
"""NLP_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tQCh-jtpZGMGlAIn1wRwaFiVmxtXhV8r
"""

# 런타임 확인
!nvidia-smi || true
!cat /etc/os-release | head
!python --version

# Ollama 설치
!sudo apt-get update && sudo apt-get install -y zstd
!curl -fsSL https://ollama.com/install.sh | sh

# 설치 확인
!ollama --version

# Ollama 서버 실행
import subprocess, time, textwrap, os, signal

# Ollama server start
proc = subprocess.Popen(["ollama", "serve"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)

# 서버가 뜰 시간을 조금 줌
time.sleep(2)

print("Ollama server started (pid):", proc.pid)

# 서버 확인
!curl -s http://127.0.0.1:11434/api/tags | head -c 500

# 모델 pull
!ollama pull llama3

import requests, json

def ollama_chat(prompt: str, model: str="llama3") -> str:
    url = "http://127.0.0.1:11434/api/chat"
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": "You are a helpful assistant for inspection process troubleshooting."},
            {"role": "user", "content": prompt}
        ],
        "stream": False,
        "options": {
            "temperature": 0.2
        }
    }
    r = requests.post(url, json=payload, timeout=600) # Increased timeout to 600 seconds
    r.raise_for_status()
    return r.json()["message"]["content"]

test_prompt = "swp 에러 로그 발생했습니다. 트러블 슈팅 가이드 간단히 3줄로."
print(ollama_chat(test_prompt, model="llama3"))

# 데이터 준비
import pandas as pd
import numpy as np

np.random.seed(42)

# ----- Constants (원하는 값으로 수정 가능) -----
EQPID = "KR-010101"
MODEL = "LGMONYTV"
Program_Version = "260206"
Equipment_Version = "M.KOR"
Spec_Min_mA = 0.80
Spec_Max_mA = 10.00

def make_row(i, label, s6f1_result, saved_result, delta_s, acw):
    return {
        "issue_id": f"{i:03d}",
        "label": label,  # OK / NG (정답 라벨)
        "EQPID": EQPID,
        "SETID": f"500MONY{i:04d}",
        "MODEL": MODEL,
        "Program_Version": Program_Version,
        "Equipment_Version": Equipment_Version,
        "S6F12_ACK": 0,
        "delta_S6F11_S6F12_s": int(delta_s),
        "S6F1_RESULT": s6f1_result,     # 장비 판단
        "ACW_Mea_mA": round(float(acw), 2),
        "Spec_Min_mA": Spec_Min_mA,
        "Spec_Max_mA": Spec_Max_mA,
        "Saved_Result": saved_result,   # 저장 결과
    }

rows = []

# ----- OK 데이터 50개 (001~050): RESULT=OK, Saved=OK -----
ok_acw = np.clip(
    np.random.normal(loc=4.5, scale=2.0, size=50),
    Spec_Min_mA + 0.01, Spec_Max_mA - 0.01
)
ok_delta = np.random.choice([1, 2, 3], size=50, p=[0.6, 0.3, 0.1])

for idx in range(1, 51):
    rows.append(make_row(idx, "OK", "OK", "OK", ok_delta[idx-1], ok_acw[idx-1]))

# ----- NG 데이터 10개 (051~060)
#  - mismatch 6개: S6F1 OK but Saved NG
#  - true NG 4개: S6F1 NG and Saved NG
ng_plan = {
    51: ("NG", "OK", "NG", 1, 3.10),
    52: ("NG", "OK", "NG", 2, 4.62),
    53: ("NG", "NG", "NG", 1, 2.40),
    54: ("NG", "OK", "NG", 3, 9.12),
    55: ("NG", "NG", "NG", 1, 6.07),
    56: ("NG", "OK", "NG", 2, 2.88),
    57: ("NG", "NG", "NG", 1, 1.05),
    58: ("NG", "OK", "NG", 2, 7.41),
    59: ("NG", "NG", "NG", 1, 3.77),
    60: ("NG", "OK", "NG", 2, 5.18),
}

for idx in range(51, 61):
    label, s6f1_result, saved_result, delta_s, acw = ng_plan[idx]
    # 스펙은 정상 찍히는 조건 유지(스펙 범위 내로 클립)
    acw = min(max(acw, Spec_Min_mA + 0.01), Spec_Max_mA - 0.01)
    rows.append(make_row(idx, label, s6f1_result, saved_result, delta_s, acw))

df = pd.DataFrame(rows)

# (선택) 파생 컬럼: mismatch 여부 / 케이스 타입
df["is_mismatch"] = ((df["S6F1_RESULT"] != df["Saved_Result"]) & (df["label"] == "NG")).astype(int)
df["case_type"] = np.where(
    df["label"] == "OK",
    "ok_normal",
    np.where(df["is_mismatch"] == 1, "mismatch_ok_saved_ng", "true_ng_s6f1_ng")
)

# ----- CSV 저장 -----
out_path = "/content/inspection_logs_60.csv"
df.to_csv(out_path, index=False, encoding="utf-8-sig")

print("Saved:", out_path)
df.head(10)

!pip -q install langchain langchain-community chromadb pypdf sentence-transformers

from langchain_community.document_loaders import PyPDFLoader
from google.colab import drive
drive.mount('/content/drive')
pdf_path = "/content/drive/MyDrive/[GW_INSTEK]GPT-9800-SERIES_USER-MANUAL_KR.pdf"
loader = PyPDFLoader(pdf_path)

documents = loader.load()
print("Total pages:", len(documents))

# 텍스트 분할
!pip install -U langchain langchain-community langchain-text-splitters
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=100,
    separators=["\n\n", "\n", " ", ""]
)

splits = splitter.split_documents(documents)

print("Total chunks:", len(splits))
print(splits[0].page_content[:500])

# 임베딩 + 벡터 DB 생성
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

vectorstore = Chroma.from_documents(
    documents=splits,
    embedding=embeddings,
    persist_directory="/content/chroma_gpt9800_manual"
)

print("Vector DB ready:", vectorstore._collection.count())

# RAG + Ollama (Vanilla + RAG Baseline)
from langchain_community.chat_models import ChatOllama

llm = ChatOllama(model="llama3", temperature=0.2)

def rag_answer_from_manual(question: str, k: int = 4):
    retriever = vectorstore.as_retriever(search_kwargs={"k": k})
    docs = retriever.invoke(question)   # 👈 여기

    context = "\n\n".join(
        [f"[MANUAL]\n{d.page_content}" for d in docs]
    )

    prompt = f"""
너는 GPT-9800 검사 장비 트러블슈팅 전문가야.
아래 MANUAL 내용만 근거로 답변해.

MANUAL:
{context}

QUESTION:
{question}

요구사항:
- 가능한 원인 2~3개
- 확인 절차(로그/S6F 시퀀스 중심) 5단계 이내
- 임시 조치 2개
"""
    return llm.invoke(prompt).content

q = "검사 프로그램에서 스캔을 했는데 검사 진행이 안돼. 원인과 조치 방법 알려줘"
print(rag_answer_from_manual(q))

from langchain.tools import tool
import pandas as pd

@tool
def manual_rag_tool(question: str) -> str:
    """
    GPT-9800 검사 장비 매뉴얼 기반 트러블슈팅 Tool.
    매뉴얼 근거로만 원인, 확인 절차, 임시 조치를 제시한다.
    """

    retriever = vectorstore.as_retriever(search_kwargs={"k": 4})
    docs = retriever.invoke(question)

    if not docs:
        return "매뉴얼에서 관련 내용을 찾지 못했습니다."

    context = "\n\n".join(
        [f"[MANUAL]\n{d.page_content}" for d in docs]
    )

    prompt = f"""
너는 GPT-9800 검사 장비 트러블슈팅 전문가야.
아래 MANUAL 내용만 근거로 답변해.

MANUAL:
{context}

QUESTION:
{question}

요구사항:
- 가능한 원인 2~3개
- 확인 절차(로그/S6F 시퀀스 중심) 5단계 이내
- 임시 조치 2개
"""

    return llm.invoke(prompt).content

from langchain.tools import tool

@tool
def inspection_log_tool(_: str) -> str:
    """
    메모리에 존재하는 inspection log DataFrame(df) 기반 분석 Tool
    """

    total = len(df)
    ng_cnt = (df["label"] == "NG").sum()
    mismatch_cnt = df["is_mismatch"].sum()

    sample = df[df["is_mismatch"] == 1][
        ["issue_id", "S6F1_RESULT", "Saved_Result", "ACW_Mea_mA"]
    ].head(5)

    result = f"""
[Inspection Summary]
- 총 검사 수량: {total}
- NG 수량: {ng_cnt}
- Mismatch 수량: {mismatch_cnt}

[Sample Mismatch Cases]
{sample.to_string(index=False)}
"""
    return result

from langchain_community.chat_models import ChatOllama

agent_llm = ChatOllama(
    model="llama3",
    temperature=0
)

!pip install --upgrade --force-reinstall langchain langchain-community

from langchain.agents import initialize_agent, AgentType
from langchain_core.messages import SystemMessage

tools = [manual_rag_tool, inspection_log_tool]

SYSTEM = SystemMessage(content=
    "너는 GPT-9800 트러블슈팅 에이전트다. "
    "반드시 tools를 사용해서 근거를 확보한 뒤 답하라. "
    "manual_rag_tool 또는 inspection_log_tool 중 최소 1개는 반드시 호출하라. "
    "매뉴얼 근거가 없으면 '매뉴얼 근거로 확인 불가'라고 답하라."
)

react_executor = initialize_agent(
    tools=tools,
    llm=agent_llm,
    agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True,
    agent_kwargs={"system_message": SYSTEM}
)

q = "검사 프로그램에서 스캔을 했는데 검사 진행이 안돼. 원인과 조치 방법 알려줘"
print(react_executor.run(q))



